import { Header } from "./_components/Header";
import "./globals.css";
import Login from "./Login";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Header>
          <Login />
        </Header>
        {children}
      </body>
    </html>
  );
}
