import Link from "next/link";
import { Header } from "./_components/Header";
import "./globals.css";
import Login from "./Login";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Header>
          <Login />
          <div>
            <a href="/">［/index］</a>
            <a href="/protected">［/protected］</a>
            <a href="/auth/login">［/auth/login］</a>
          </div>
        </Header>
        {children}
      </body>
    </html>
  );
}
